name: ci

on:
  push:
    branches:
      - 'master'
      - 'cleaned'
      - 'full'
  schedule:
    # Daily
    - cron: '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        if: github.ref_name == 'master'
        name: Build and push slim tag
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          tags: frolvlad/alpine-fpc:slim
          cache-from: type=registry,ref=frolvlad/alpine-fpc:slim
          cache-to: type=inline
      - 
        if: github.ref_name == 'cleaned'
        name: Build and push cleaned tag
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          tags: frolvlad/alpine-fpc:latest,frolvlad/alpine-fpc:cleaned
          cache-from: type=registry,ref=frolvlad/alpine-fpc:cleaned
          cache-to: type=inline
      - 
        if: github.ref_name == 'full'
        name: Build and push full tag
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          tags: frolvlad/alpine-fpc:full
          cache-from: type=registry,ref=frolvlad/alpine-fpc:full
          cache-to: type=inline
